### ISSUE TITLE
Info aggiornamento dati

### ISSUE THREAD

**Issue by chuck2098** [CloudItaly/Indice-RT#1]
Salve,
Volevo sapere se questi dati sono ufficiali e verranno aggiornati ad ogni variazione degli indici rt e dei colori delle regioni.

Grazie, saluti

**Comment by CloudItaly** [comment]
Ciao. I dati li copio-incollo dal PDF che viene pubblicato qui, ogni settimana:
http://www.salute.gov.it/portale/nuovocoronavirus/archivioNotizieNuovoCoronavirus.jsp?lingua=italiano&tipo=Report+settimanale+Covid-19&btnCerca=cerca

Per i colori delle regioni, cerco di vederli dai vari comunicati/news che si leggono nella rete.

**Comment by chuck2098** [comment]
La ringrazio, ottimo lavoro!
Cercavo una repo che mi fornisse questi dati per poi integrarli nella mia app.

**Comment by CloudItaly** [comment]
Diamoci del tu, se non te ne dispiace. 
Visto che oggi c'è un utilizzatore della mia repo, ho provveduto ad effettuare queste modifiche:

1) Rinominato: **Trentino Alto Adige/PA Trento** in **PA Trento**
2) Uniformata la dicitura delle note. 

Ho anche notato che inizialmente riportavo la stima dell'rt, poi via via ho corretto riportando il valore corretto (quello IND3.2).Ho colto quindi occasione per correggerli tutti.

**Comment by chuck2098** [comment]
Certo!
Perfetto.
Grazie mille, in questo modo evito alcuni controlli lato client.
In ogni caso, dovessi notare qualche incongruenza o discrepanza, te la faccio presente, in maniera tale da darti una mano sul controllo del dataset.

Saluti.
