### ISSUE TITLE
Sintassi errata report #85

### ISSUE THREAD

**Issue by alexmonti19** [CloudItaly/Indice-RT#10]
Ciao, e innanzitutto grazie per il tuo lavoro! :)

Ho notato oggi che l'ultimo elemento in "File-JSON.json" contiene degli errori di sintassi a partire dalla riga 1589: mancano le virgole a separare i campi (oltre ad alcuni rt vuoti, ma non so se questo possa essere considerato un errore).

Alex

**Comment by alexmonti19** [comment]
Ho notato ora che manca anche l'Umbria. Probabilmente c'e' stato qualche errore nel parsing del pdf.

**Comment by CloudItaly** [comment]
Grazie per il contributo e per la segnalazione. Ho provveduto a correggere a mano, in attesa di correggere proprio il file che mi dovrebbe aiutare a  non commettere questi errori :D

**Comment by alexmonti19** [comment]
Perfetto, grazie ancora :)
