### ISSUE TITLE
Info indice Rt

### ISSUE THREAD

**Issue by alexmonti19** [CloudItaly/Indice-RT#4]
Ciao! 
Innanzitutto grazie per il lavoro di condivisione e aggiornamento dei dati :)

La mia domanda è sull'indice Rt, magari esaminando i pdf del governo ci sei già incappato: l'indice Rt "nazionale" che riportano quotidiani e giornali, da dove viene preso?
Oltre agli indici regionali mi piacerebbe infatti avere anche il dato a livello nazionale, ma non sono riuscito a capire se i numeri che si leggono in giro provengono da una qualche indicazione ufficiale del governo o se banalmente possono essere ricavati come media degli Rt regionali.

**Comment by CloudItaly** [comment]
Ciao! Dico la mia. In rete, si tende sempre a fare copia-incolla. Importante è fare clickbait. 

Io infatti aspetto sempre i comunicati o la pubblicazione dei PDF, per avere la correttezza dell'informazione. Poco mi interessa diffonderla per prima. Sai quante volte ho letto di cambi di colore (da lunedi...) quando entravano in vigore già dalla domenica?

**Comment by alexmonti19** [comment]
Immaginavo, penso facciano una media di qualche genere sugli Rt regionali a questo punto.

Grazie ancora :)
