### ISSUE TITLE
Report settimanale

### ISSUE THREAD

**Issue by darioBeugu** [CloudItaly/Indice-RT#5]
Il sistema per aggiornare i dati del report settimanale è automatico? Perchè ho visto che è uscito l'ultimo oggi (n. 43).
Grazie.

**Comment by CloudItaly** [comment]
Si sto per inserire i dati.

**Comment by darioBeugu** [comment]
Grazie mille per il tuo lavoro!
Sto utilizzando i tuoi dati nella mia applicazione. 
https://play.google.com/store/apps/details?id=com.dario.eugu.DatiNazionali 

A breve aggiungerò tra le fonti il repository direttamente.
