### ISSUE TITLE
Dati mancanti per 2020 per colori regioni

### ISSUE THREAD

**Issue by jumpjack** [CloudItaly/Indice-RT#7]
Il file colori.json contiene dati a partire dal 16 gennaio 2021, ma le ordinanze delle zone sono iniziate a novembre 2020.

**Comment by CloudItaly** [comment]
Lo so ma la voglia di monitorare per scopi personali, mi sarebbe venuta successivamente e non avendo mezzi automatici per recuperare i dati, mi son basato su quello che ho trovato dopo e l'ho aggiornato via via.
